# Generated by Django 3.2.4 on 2021-06-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='https://drive.google.com/drive/folders/1xMGz220SA1DFAFrlfSEli7-DAoaO0tJf?usp=sharing'),
        ),
    ]
